udaysinghcode/superscript

- src/ast.ml
Hi I just added two comments for work on the ast.
> added todos for ast

- src/parser.mly
Adding parser.mly with arithmetic operators, parens, assignment for literals and identifiers
> Adding parser.mly

- src/scanner.mll
Adding scanner that parses tokens for parens, +-*/, assignment, literals, identifiers and EOF
> Adding scanner

- src/parser.mly
Rewriting parser.mly to work with the Udays AST grammar
> Changes to parser.mly to work with Uday's Ast.ml

- src/scanner.mll
> Setup scanner

- src/parser.mly
Parser works with int, (sexpr), identifier and string
> Parser works with int, (sexpr), identifier and string

- src/parser.mly
- src/scanner.mll
UPDATING TO SCAN INT, FLOAT, STRING, ID
> Updating scanner and parser to scan int, float, string, id

- src/scanner.mll
Changing names of binary operators and equality comparators in Scanner
> Change ops names

- src/scanner.mll
Adding true/false tokens to scanner. Also matches quoted Strings. Adding comments about tokens matched.
> Add true/false tokens to scanner; also scans for quoted Strings

- src/scanner.mll
> fixing problems in scanner.mll

- src/helloworld.c
> Caramel tests

- src/parser.mly
- src/preprocessor.mll
- src/scanner.mll
Updating let expression syntax to "let a b c" instead of "let a b in c" -- removing the "in"
> Removing in

- src/ast.ml
- src/parser.mly
- src/scanner.mll
Do not merge until after presentation - but unary minus is working now
> Scanner fix

- src/ast.ml
> Ast parser changes

- src/executor.ml
- src/type_infer.ml
Changes to executor/type infer for assignment. Also now prints the list of all variables and their types.
> Type infer

- src/ast.ml
- src/executor.ml
- src/type_infer.ml
Type inference works for user-defined functions and anonymous functions.
> Type infer - handling functions

- src/executor.ml
- src/generator.ml
- src/parser.mly
- src/type_infer.ml
Type infer - typing for built-in functions, and recursion works now
> Type infer - typing for built-in functions, and recursion works now

- src/ast.ml
- src/parser.mly
- src/scanner.mll
- src/type_infer.ml
Type infer - refactor, reduce warnings, add exec/do and additional invalid args checks
> Type infer - refactor, reduce warnings, add exec/do and additional invalid args checks

- src/executor.ml
- src/fib.c
- src/generator.ml
- src/make
- src/message.ml
- src/parser.mly
- src/preprocessor.mll
- src/scanner.mll
- src/type_infer.ml
Also fixing some issues parser/scanner, and adding fib.c for testing the preprocessor
> Fix recursion, add error msg detail, output .ss file with preprocessor

- src/type_infer.ml
fixing but with List.nth index out of bounds errors
> Js object type
